// Mocks generated by Mockito 5.3.2 from annotations
// in event_sync/test/feature/data/repositories/event_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:event_sync/src/core/data/id_generator.dart' as _i10;
import 'package:event_sync/src/core/domain/config_options.dart' as _i9;
import 'package:event_sync/src/core/time/time_info.dart' as _i11;
import 'package:event_sync/src/feature/data/local/data_sources/config_local_data_source.dart'
    as _i8;
import 'package:event_sync/src/feature/data/local/data_sources/event_local_data_source.dart'
    as _i6;
import 'package:event_sync/src/feature/data/local/models/config_model.dart'
    as _i3;
import 'package:event_sync/src/feature/data/local/models/event_model.dart'
    as _i7;
import 'package:event_sync/src/feature/data/remote/data_sources/event_remote_data_source.dart'
    as _i4;
import 'package:event_sync/src/feature/data/remote/models/remote_event_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRemoteEventModel_0 extends _i1.SmartFake
    implements _i2.RemoteEventModel {
  _FakeRemoteEventModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfigModel_1 extends _i1.SmartFake implements _i3.ConfigModel {
  _FakeConfigModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_2 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EventRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRemoteDataSource extends _i1.Mock
    implements _i4.EventRemoteDataSource {
  MockEventRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.RemoteEventModel>> getEvents({
    required Uri? host,
    required String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvents,
          [],
          {
            #host: host,
            #token: token,
          },
        ),
        returnValue: _i5.Future<List<_i2.RemoteEventModel>>.value(
            <_i2.RemoteEventModel>[]),
      ) as _i5.Future<List<_i2.RemoteEventModel>>);
  @override
  _i5.Future<_i2.RemoteEventModel> createEvent(
    _i2.RemoteEventModel? event, {
    required Uri? host,
    required String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [event],
          {
            #host: host,
            #token: token,
          },
        ),
        returnValue:
            _i5.Future<_i2.RemoteEventModel>.value(_FakeRemoteEventModel_0(
          this,
          Invocation.method(
            #createEvent,
            [event],
            {
              #host: host,
              #token: token,
            },
          ),
        )),
      ) as _i5.Future<_i2.RemoteEventModel>);
}

/// A class which mocks [EventLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventLocalDataSource extends _i1.Mock
    implements _i6.EventLocalDataSource {
  MockEventLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> cacheEvent(_i7.EventModel? model) => (super.noSuchMethod(
        Invocation.method(
          #cacheEvent,
          [model],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<List<_i7.EventModel>> getAllEvents() => (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue: _i5.Future<List<_i7.EventModel>>.value(<_i7.EventModel>[]),
      ) as _i5.Future<List<_i7.EventModel>>);
  @override
  _i5.Future<void> deleteEvent(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [eventId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ConfigLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigLocalDataSource extends _i1.Mock
    implements _i8.ConfigLocalDataSource {
  MockConfigLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> write(_i3.ConfigModel? model) => (super.noSuchMethod(
        Invocation.method(
          #write,
          [model],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<_i3.ConfigModel> read(_i9.ConfigOption? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [key],
        ),
        returnValue: _i5.Future<_i3.ConfigModel>.value(_FakeConfigModel_1(
          this,
          Invocation.method(
            #read,
            [key],
          ),
        )),
      ) as _i5.Future<_i3.ConfigModel>);
  @override
  _i5.Future<void> delete(_i9.ConfigOption? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [IdGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdGenerator extends _i1.Mock implements _i10.IdGenerator {
  MockIdGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String generateId() => (super.noSuchMethod(
        Invocation.method(
          #generateId,
          [],
        ),
        returnValue: '',
      ) as String);
}

/// A class which mocks [TimeInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimeInfo extends _i1.Mock implements _i11.TimeInfo {
  MockTimeInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime now() => (super.noSuchMethod(
        Invocation.method(
          #now,
          [],
        ),
        returnValue: _FakeDateTime_2(
          this,
          Invocation.method(
            #now,
            [],
          ),
        ),
      ) as DateTime);
}
